## (1) 기본 자료형

In [1]:
import numpy as np
data=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(data)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
a.dtype

dtype('int32')

In [3]:
type(a)

numpy.ndarray

In [4]:
a=a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [5]:
a[0][1]

2.0

In [6]:
a[0]

array([1., 2., 3.], dtype=float32)

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [11]:
np.nan*10

nan

In [12]:
a[0][1]=np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [13]:
a*10

array([[10., nan, 30.],
       [40., 50., 60.],
       [70., 80., 90.]], dtype=float32)

In [14]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a[0][1]=np.nan   #nan은 int에서는 사용할 수 없다. float에만 사용

ValueError: cannot convert float NaN to integer

In [17]:
# 1~10 사이의 실수 20개
a=np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## (2) 연산

In [18]:
data=np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
data*data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
data-data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
data/data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [24]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [25]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## (3)차원

* 다차원(ndarray)

In [26]:
# 0차원: 스칼라
a=np.array(1)
print(a)
print(a.shape)
print(a.ndim)   # 몇차원인지?

1
()
0


In [27]:
# 1차원: 벡터
a=np.array([1])
print(a)
print(a.shape)
print(a.ndim) 

[1]
(1,)
1


In [28]:
# 1차원: 벡터
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)  # 5개의 형태
print(a.ndim) 

[1 2 3 4 5]
(5,)
1


In [29]:
# 2차원: 메트릭스
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)   # 2행 3열
print(a.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [30]:
# 2차원: 메트릭스
a=np.array([[1]])
print(a)
print(a.shape)   
print(a.ndim) 

[[1]]
(1, 1)
2


In [31]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2]
 [3 4]]
(2, 2)
2


In [32]:
# 3차원 : 3차원 이상의 다차원의 행렬을 Tensor
# TensorFlow : 다차원 행렬을 가지고 있는 연산을 해서 어떤 결과를 도출해 내는 것

a=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(a)
print(a.shape)
print(a.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


## (4) matrix 유형

In [33]:
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [34]:
b=np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
b=np.ones(12).reshape(2,3,2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [36]:
c=np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
c=np.zeros([3,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
d=np.eye(3)   # 단위 행렬
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
e=np.full([3,4],1000)
e

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [40]:
# linspace : 1차원 배열 만들기, 예를 들어 그래프에서 수평축의 간격을 만들때 편리
f=np.linspace(1,10,4) 
f

array([ 1.,  4.,  7., 10.])

## (5) 집계함수

In [41]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
a[0][0]=100
a[0][1]=1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [43]:
np.mean(a)

114.4

In [44]:
np.median(a)

6.5

In [45]:
np.std(a)

296.5485457728633

In [46]:
np.var(a)

87941.04

In [47]:
np.sum(a)

1144

In [48]:
np.max(a)

1000

In [49]:
np.min(a)

2

In [50]:
np.sum(a,axis=0)    # sum(a)

array([ 105, 1006,    9,   11,   13])

In [51]:
np.sum(a,axis=1)

array([1109,   35])

In [52]:
lit=[2,3,5,6,4]
print(np.mean(lit))
print(np.var(lit))
print(np.std(lit))

4.0
2.0
1.4142135623730951
